### PR TITLE
Remove runtime dependency on typing_extensions package

### PR DESCRIPTION
**Pull request by johnslavik**
A few improvements to package typing.

I removed the runtime dependency on the `typing_extensions` package.

See also https://github.com/python-poetry/poetry/pull/9251 where I promoted that practice.

### CODE REVIEW

**Comment by johnslavik** [comment]
I wanted to move type aliases to the `if TYPE_CHECKING` branch, but that would pose some problems to those who don't use PEP 563.

**Comment by johnslavik** [comment]
@willmcgugan Let me know if you are interested in moving `@overload`s to `if TYPE_CHECKING` branches like here: https://github.com/jaraco/path/pull/224/files.

**Comment by willmcgugan** [comment]
Thanks.

What is the benefit of moving overloads inside a `if TYPE_CHECKING` block? Faster import?

**Comment by johnslavik** [comment]
> Thanks.
> 
> What is the benefit of moving overloads inside a `if TYPE_CHECKING` block? Faster import?

I'd say less runtime overhead and less namespace mess (you don't have runtime access of typing-only `overload` and you don't create a few functions that are to be inexistent just a few moments later). For such a small library like this, it might not be necessary, but just showing that it's feasible.

**Pull request merged**
